name: Release

on:
  pull_request_target:
    types: [closed]

jobs:
  release_job:
    uses: bedita/github-workflows/.github/workflows/release.yml@feat/output-release
    with:
      main_branch: '5-salix'
      dist_branches: '["5-salix","4-cactus"]'
      version_ini_path: plugins/BEdita/Core/config/bedita.ini
      version_ini_prefix: "[BEdita]\nversion = "

  filter_tree:
    needs: release_job
    uses: ./.github/workflows/filter-components.yml
    secrets: inherit

  docker_push:
    needs: release_job
    steps:
      - uses: actions/checkout@v3
        name: Check out code

      - uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: bedita/bedita
          registry: docker.io
          tag: ${{ needs.release_job.outputs.version }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
